[tool.isort]
profile = "black"
skip_glob = ["font/*"]

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = "font"

[tool.pytest.ini_options]
norecursedirs = 'font/*'
addopts = "-s"
